server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qlsv
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: Jack5cu$
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true




